version: '3.8'

services:
  backend:
    build:
      context: ./api_flask
    ports:
      - "8132:8132"              # era "5000:5000"
    volumes:
      - ./api_flask:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./front-end/project-interface
    ports:
      - "3001:80" 
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8132
