version: '3.8'

services:
  backend:
    build:
      context: ./api_flask
    ports:
      - "8121:8121"  # Porta 8121 no host mapeada para a 8132 no container
    volumes:
      - ./api_flask:/app
    environment:
      - FLASK_ENV=development
    networks:
      - my-network

  frontend:
    build:
      context: ./front-end/project-interface
    ports:
      - "8120:80"  # Porta 8120 no host mapeada para a 80 no container
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

